trigger:
- develop
- master

resources:
  repositories:
  - repository: pipeline-template
    type: git
    name: "EliteMobile/devops-pipeline-template"

stages: 
- stage: publish_artifact_develop
  displayName: Publish npm package on Azure DevOps Artifact with next tag
  # condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-latest'
    workspace:
      clean: all
    steps:
    
    - template: frontend/steps-npm-publish.yaml
      parameters:
        publishTag: next