trigger:
- develop
- master

stages: 
- stage: publish_artifact_develop
  displayName: Publish npm package on Azure DevOps Artifact with next tag
  # condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-latest'
    workspace:
      clean: all
    steps:
    
    - task: Npm@1
      displayName: 'publish next version'
      inputs:
          command: 'custom'
          customCommand: 'publish --tag next'
          publishRegistry: 'useFeed'
          publishFeed: 'elitemobile-feed'
          workingDir: '.'