trigger:
- develop
- master

variables:
  publicCdnAccountStorageName: 'emobtstcdnstorage'
  publicCdnAccountStorageKey: $(tst_storage_key)
  privateCdnAccountStorageName: 'emobdevcdnstorage'
  privateCdnAccountStorageKey: $(dev_storage_key)
  packageName: 'videojs-contrib-eme'
  exposeStyleGuide: true

resources:
  repositories:
  - repository: pipeline-template
    type: git
    name: "EliteMobile/devops-pipeline-template"

stages:
- template: /frontend/default-artifact-pipeline.yaml@pipeline-template
  parameters:
    publicCdnAccountStorageName: ${{ variables.publicCdnAccountStorageName }}
    publicCdnAccountStorageKey: ${{ variables.publicCdnAccountStorageKey }}
    privateCdnAccountStorageName: ${{ variables.privateCdnAccountStorageName }}
    privateCdnAccountStorageKey: ${{ variables.privateCdnAccountStorageKey }}
    packageName: ${{ variables.packageName }}
    exposeStyleGuide: ${{ variables.exposeStyleGuide }}